### ISSUE TITLE
Where is the src path for installing custom/user plugins?

### ISSUE THREAD

**Issue by ragedriver** [NullCub3/aur-vencord-installer-bin#2]
I know this is a dumb question,but im on arch linux and I am trying to install some custom plugins and I cant find the src/plugins folder path. I tried vesktop,official discord with injecting vencord and this aur script aswell. I cant seem to find it,am I dont something wrong?

**Comment by nullcubee** [comment]
Plugins with Vencord are integrated into Vencord itself, so if you want to add custom plugins you’ll have to build it from the source code. This AUR package only downloads the Vencord installer, so I don’t think this will help you a ton.

I’m also not a Vencord plugin developer, so I couldn’t tell you how exactly to go about working with this stuff but the actual Vencord devs have a documentation website which has a bunch of information about the topic:
https://docs.vencord.dev/

And as for installing custom plugins, I believe this page might be of some use:
https://docs.vencord.dev/installing/custom-plugins/

Best of luck!
